// Implementation file for parser generated by fsyacc
module CreateTableParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "CreateTableParser.fsp"
   
open Sql   

# 10 "CreateTableParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | INT
  | DOUBLE
  | STRING
  | CBRCK
  | OBRCK
  | EOF
  | TABLE
  | CREATE
  | COMMA
  | ID of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_INT
    | TOKEN_DOUBLE
    | TOKEN_STRING
    | TOKEN_CBRCK
    | TOKEN_OBRCK
    | TOKEN_EOF
    | TOKEN_TABLE
    | TOKEN_CREATE
    | TOKEN_COMMA
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstartCT
    | NONTERM_startCT
    | NONTERM_columnTypeList
    | NONTERM_columnType

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | INT  -> 0 
  | DOUBLE  -> 1 
  | STRING  -> 2 
  | CBRCK  -> 3 
  | OBRCK  -> 4 
  | EOF  -> 5 
  | TABLE  -> 6 
  | CREATE  -> 7 
  | COMMA  -> 8 
  | ID _ -> 9 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_INT 
  | 1 -> TOKEN_DOUBLE 
  | 2 -> TOKEN_STRING 
  | 3 -> TOKEN_CBRCK 
  | 4 -> TOKEN_OBRCK 
  | 5 -> TOKEN_EOF 
  | 6 -> TOKEN_TABLE 
  | 7 -> TOKEN_CREATE 
  | 8 -> TOKEN_COMMA 
  | 9 -> TOKEN_ID 
  | 12 -> TOKEN_end_of_input
  | 10 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstartCT 
    | 1 -> NONTERM_startCT 
    | 2 -> NONTERM_columnTypeList 
    | 3 -> NONTERM_columnTypeList 
    | 4 -> NONTERM_columnType 
    | 5 -> NONTERM_columnType 
    | 6 -> NONTERM_columnType 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 12 
let _fsyacc_tagOfErrorTerminal = 10

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | INT  -> "INT" 
  | DOUBLE  -> "DOUBLE" 
  | STRING  -> "STRING" 
  | CBRCK  -> "CBRCK" 
  | OBRCK  -> "OBRCK" 
  | EOF  -> "EOF" 
  | TABLE  -> "TABLE" 
  | CREATE  -> "CREATE" 
  | COMMA  -> "COMMA" 
  | ID _ -> "ID" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | INT  -> (null : System.Object) 
  | DOUBLE  -> (null : System.Object) 
  | STRING  -> (null : System.Object) 
  | CBRCK  -> (null : System.Object) 
  | OBRCK  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | TABLE  -> (null : System.Object) 
  | CREATE  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 5us; 6us; 2us; 65535us; 5us; 9us; 10us; 11us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 5us; 1us; 6us; 1us; 6us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 15us; 17us; 19us; 21us; 23us; 25us; 27us; 29us; 31us; 33us; 35us; |]
let _fsyacc_action_rows = 18
let _fsyacc_actionTableElements = [|1us; 32768us; 7us; 2us; 0us; 49152us; 1us; 32768us; 6us; 3us; 1us; 32768us; 9us; 4us; 1us; 32768us; 4us; 5us; 3us; 32768us; 0us; 12us; 1us; 14us; 2us; 16us; 2us; 32768us; 3us; 7us; 8us; 10us; 1us; 32768us; 5us; 8us; 0us; 16385us; 0us; 16386us; 3us; 32768us; 0us; 12us; 1us; 14us; 2us; 16us; 0us; 16387us; 1us; 32768us; 9us; 13us; 0us; 16388us; 1us; 32768us; 9us; 15us; 0us; 16389us; 1us; 32768us; 9us; 17us; 0us; 16390us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 2us; 3us; 5us; 7us; 9us; 13us; 16us; 18us; 19us; 20us; 24us; 25us; 27us; 28us; 30us; 31us; 33us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 7us; 1us; 3us; 2us; 2us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16385us; 16386us; 65535us; 16387us; 65535us; 16388us; 65535us; 16389us; 65535us; 16390us; |]
let _fsyacc_reductions ()  =    [| 
# 128 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Sql.createTableStatement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstartCT));
# 137 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnTypeList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 22 "CreateTableParser.fsp"
                                                     
                                                     { Table = _3;
                                                       ColumnList = List.rev _5
                                                      }   
                                                 
                   )
# 22 "CreateTableParser.fsp"
                 : Sql.createTableStatement));
# 153 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnType)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "CreateTableParser.fsp"
                                                           [_1] 
                   )
# 29 "CreateTableParser.fsp"
                 : 'columnTypeList));
# 164 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnTypeList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnType)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "CreateTableParser.fsp"
                                                             _3 :: _1 
                   )
# 30 "CreateTableParser.fsp"
                 : 'columnTypeList));
# 176 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "CreateTableParser.fsp"
                                    IntCType, _2 
                   )
# 33 "CreateTableParser.fsp"
                 : 'columnType));
# 187 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "CreateTableParser.fsp"
                                       DoubleCType, _2 
                   )
# 34 "CreateTableParser.fsp"
                 : 'columnType));
# 198 "CreateTableParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "CreateTableParser.fsp"
                                       StringCType, _2 
                   )
# 35 "CreateTableParser.fsp"
                 : 'columnType));
|]
# 210 "CreateTableParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 13;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let startCT lexer lexbuf : Sql.createTableStatement =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
